name: Build CMake Target
inputs:
  build-dir:
    required: true
  config:
    required: true
  configure-args:
    default: ''
  generator:
    required: true
  target:
    required: true
runs:
  using: composite
  steps:
  - name: Configure CMake
    shell: bash
    run: |
      cmake . -B "${{ inputs.build-dir }}" \
              -G "${{ inputs.generator }}" \
              -DCMAKE_CONFIGURATION_TYPES=${{ inputs.config }} \
              ${{ inputs.configure-args }}

  - name: Build ${{ inputs.target }}
    shell: bash
    run: |
      cmake --build "${{ inputs.build-dir }}" \
            --target "${{ inputs.target }}" \
            --config "${{ inputs.config }}"
