name: Build CMake
inputs:
  target:
    required: true
  generator:
    required: true
  config:
    required: true
runs:
  using: composite
  steps:
  - name: Generate Projects
    shell: bash
    run: |
      cmake . -B cmake-build \
              -G "${{ inputs.generator }}" \
              -DJUCE_BUILD_EXAMPLES=ON \
              -DJUCE_BUILD_EXTRAS=ON

  - name: Build projects
    shell: bash
    run: |
      cmake --build cmake-build \
            --target ${{ inputs.target }} \
            --config ${{ inputs.config }}
