name: Build Linux Project
inputs:
  project-dir:
    required: true
  config:
    required: true
  compiler:
    required: true
outputs:
  build-dir:
    value: ${{ inputs.project-dir }}/Builds/LinuxMakefile/build
runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: ./.github/actions/install-linux-dependencies

  - name: Build LinuxMakefile
    shell: bash
    working-directory: ${{ inputs.project-dir }}/Builds/LinuxMakefile
    run: make -j$(nproc) CONFIG=${{ inputs.config }} V=1 CXXFLAGS="-Werror" CXX="${{ inputs.compiler }}"
