name: 'Build Xcode project'
inputs:
  project:
    required: true
  config:
    required: true
    default: Release
runs:
  using: "composite"
  steps:
    run: |
      xcodebuild -project ${{ inputs.project }} \
                 -configuration ${{ inputs.config }} \
                 GCC_TREAT_WARNINGS_AS_ERRORS=YES
