name: Build macOS Project
inputs:
  project-dir:
    required: true
  config:
    required: true
outputs:
  build-dir:
    value: ${{ inputs.project-dir }}/Builds/MacOSX/build/${{ inputs.config }}
runs:
  using: composite
  steps:
  - name: Build project
    shell: bash
    working-directory: ./${{ inputs.project-dir }}/Builds/MacOSX
    run: |
      xcodebuild -configuration ${{ inputs.config }} \
                 GCC_TREAT_WARNINGS_AS_ERRORS=YES
