name: Build LinuxMakefile
inputs:
  project-dir:
    required: true
  project-name:
    required: true
  exporter:
    default: VisualStudio2022
  config:
    required:
outputs:
  build-dir:
    value: ${{ inputs.project-dir }}/Builds/${{ inputs.exporter }}/x64/${{ inputs.config }}
runs:
  using: composite
  steps:
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.1

  - name: Build project
    shell: pwsh
    working-directory: ${{ inputs.project-dir }}/Builds/${{ inputs.exporter }}
    run: msbuild ${{ inputs.project-name }}.sln /t:Build /p:Configuration=${{ inputs.config }} /warnaserror /maxcpucount
