name: Install an Apple Signing Certificate to the key-chain
inputs:
  certificate-base64:
    required: true
  certificate-password:
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    env:
      CERTIFICATE_BASE64: ${{ inputs.certificate-base64 }}
      CERTIFICATE_PASSWORD: ${{ inputs.certificate-password }}
    run: |
      CERTIFICATE_PATH=${RUNNER_TEMP}/certificate.p12
      KEYCHAIN_PATH=${RUNNER_TEMP}/app-signing.keychain-db
      KEYCHAIN_PASSWORD=${RANDOM}-${RANDOM}-${RANDOM}-${RANDOM}
      echo -n "${CERTIFICATE_BASE64}" | base64 --decode -o ${CERTIFICATE_PATH}
      security create-keychain -p "${KEYCHAIN_PASSWORD}" ${KEYCHAIN_PATH}
      security set-keychain-settings -lut 21600 ${KEYCHAIN_PATH}
      security unlock-keychain -p "${KEYCHAIN_PASSWORD}" ${KEYCHAIN_PATH}
      security import ${CERTIFICATE_PATH} -P "${CERTIFICATE_PASSWORD}" -A -t cert -f pkcs12 -k ${KEYCHAIN_PATH}
      security list-keychain -d user -s ${KEYCHAIN_PATH}
