name: Install an iOS Provisioning Profile
inputs:
  profile-base64:
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    env:
      PROFILE_BASE64: ${{ inputs.profile-base64 }}
    run: |
      PROFILES_PATH="~/Library/MobileDevice/Provisioning Profiles"
      mkdir -p "${PROFILES_PATH}"
      echo -n "${PROFILE_BASE64}" | base64 --decode -o "${PROFILES_PATH}/profile.mobileprovision"
