name: Build Android Project
inputs:
  project-dir:
    required: true
  config:
    required: true
runs:
  using: composite
  steps:
  - name: Set up JDK
    uses: actions/setup-java@v3
    with:
      java-version: 17
      distribution: temurin
      cache: gradle

  - name: Generate debug keystore
    shell: bash
    run: |
      mkdir ~/.android
      cd ~/.android
      keytool -genkey \
              -v \
              -keystore debug.keystore \
              -storepass android \
              -alias androiddebugkey \
              -keypass android \
              -keyalg RSA \
              -keysize 2048 \
              -validity 10000 \
              -dname "cn=Android Debug, ou=Android, o=Android, c=UK"

  - name: Enable warning as error
    shell: bash
    working-directory: ${{ inputs.project-dir }}/Builds/Android/app
    run: echo -e '\ntarget_compile_options( ${BINARY_NAME} PRIVATE -Werror )' >> "CMakeLists.txt"

  - name: Build project
    shell: bash
    working-directory: ${{ inputs.project-dir }}/Builds/Android
    run: ./gradlew --parallel --max-workers=$(nproc) assemble${{ inputs.config }}
