name: Android builds
on: push

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-generate:
    name: Generate CMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate CMake
        uses: ./.github/actions/cmake-generate
        with:
          generator: Ninja

  cmake-builds:
    needs: cmake-generate
    strategy:
      matrix:
        target: [AudioPerformanceTest,
                 AudioPluginHost,
                 DemoRunner,
                 NetworkGraphicsDemo,
                 GuiAppExample]
    name: ${{ matrix.target }} (CMake)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build CMake target ${{ matrix.target }}
        uses: ./.github/actions/cmake-build
        with:
          target: ${{ matrix.target }}

  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPerformanceTest},
          {dir: extras, name: AudioPluginHost},
          {dir: extras, name: NetworkGraphicsDemo}
        ]
        config: [Debug, Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: ubuntu-latest
    env:
      ANDROID_PATH: ~/.android
      PROJECT_PATH: ./${{ matrix.project.dir }}/${{ matrix.project.name }}/Builds/LinuxMakefile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Create ${{ env.ANDROID_PATH }} directory
        run: mkdir ${{ env.ANDROID_PATH }}

      - name: Generate debug keystore
        working-directory: ${{ env.ANDROID_PATH }}
        run: |
          keytool -genkey \
                  -v \
                  -keystore debug.keystore \
                  -storepass android \
                  -alias androiddebugkey \
                  -keypass android \
                  -keyalg RSA \
                  -keysize 2048 \
                  -validity 10000 \
                  -dname "cn=Android Debug, ou=Android, o=Android, c=UK"

      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: ./gradlew --parallel --max-workers=$(nproc) assemble${{ matrix.config }}
