name: Android builds
on: push

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPluginHost}
        ]
        config: [Debug, Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ${{ matrix.project.name }}
        uses: ./.github/actions/build-android
        with:
          project-dir: ./${{ matrix.project.dir }}/${{ matrix.project.name }}
          config: ${{ matrix.config }}
