name: iOS builds
on: push

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-generate:
    name: Generate CMake
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate CMake
        uses: ./.github/actions/generate-cmake
        with:
          generator: Xcode
          args: -DCMAKE_SYSTEM_NAME=iOS

  cmake-builds:
    needs: cmake-generate
    strategy:
      matrix:
        target: [GuiAppExample]
        config: [Release]
    name: ${{ matrix.target }} (CMake)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build CMake target ${{ matrix.target }}
        uses: ./.github/actions/build-cmake
        with:
          config: ${{ matrix.config }}
          target: ${{ matrix.target }}
          args: -sdk iphonesimulator

  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPluginHost}
        ]
        config: [Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: macos-latest
    env:
      PROJECT_PATH: ./${{ matrix.project.dir }}/${{ matrix.project.name }}/Builds/iOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          xcodebuild -configuration ${{ matrix.config }} \
                     -sdk iphonesimulator \
                     GCC_TREAT_WARNINGS_AS_ERRORS=YES
