name: iOS builds
on: push

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPluginHost}
        ]
        config: [Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: macos-latest
    env:
      PROJECT_PATH: ./${{ matrix.project.dir }}/${{ matrix.project.name }}/Builds/iOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          xcodebuild -configuration ${{ matrix.config }} \
                     -sdk iphonesimulator \
                     GCC_TREAT_WARNINGS_AS_ERRORS=YES
