name: Linux builds
on: push

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-builds:
    strategy:
      matrix:
        target: [AudioPluginExample,
                 ConsoleAppExample,
                 GuiAppExample]
        config: [Debug, Release]
    name: ${{ matrix.target }} (CMake - ${{ matrix.config }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-linux-dependencies

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Build CMake target ${{ matrix.target }}
        uses: ./.github/actions/build-cmake
        with:
          build-dir: ./cmake-build
          generator: Ninja Multi-Config
          config: ${{ matrix.config }}
          target: ${{ matrix.target }}
          configure-args: -DJUCE_BUILD_EXAMPLES=ON

  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPerformanceTest},
          {dir: extras, name: AudioPluginHost},
          {dir: extras, name: BinaryBuilder},
          {dir: extras, name: NetworkGraphicsDemo},
          {dir: extras, name: Projucer},
          {dir: extras, name: UnitTestRunner},
        ]
        config: [Debug, Release]
        compiler: [g++, clang++]
    name: ${{ matrix.project.name }} (${{ matrix.compiler }} ${{ matrix.config }})
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ./${{ matrix.project.dir }}/${{ matrix.project.name }}/Builds/LinuxMakefile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-linux-dependencies

      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: make -j$(nproc) CONFIG=${{ matrix.config }} V=1 CXXFLAGS="-Werror" CXX="${{ matrix.compiler }}"

      - if: matrix.project.name == 'UnitTestRunner'
        name: Run UnitTestRunner
        run: ${{ env.PROJECT_PATH }}/build/UnitTestRunner
