name: macOS builds
on:
  push:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-builds:
    strategy:
      matrix:
        target: [AudioPluginExample,
                 ConsoleAppExample,
                 GuiAppExample]
        config: [Release]
    name: ${{ matrix.target }} (CMake - ${{ matrix.config }})
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build CMake target ${{ matrix.target }}
        uses: ./.github/actions/build-cmake
        with:
          build-dir: ./cmake-build
          generator: Xcode
          config: ${{ matrix.config }}
          target: ${{ matrix.target }}
          configure-args: -DJUCE_BUILD_EXAMPLES=ON

  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPluginHost},
          {dir: extras, name: Projucer},
          {dir: extras, name: UnitTestRunner},
        ]
        config: [Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ${{ matrix.project.name }}
        uses: ./.github/actions/build-macos
        id: build
        with:
          project-dir: ./${{ matrix.project.dir }}/${{ matrix.project.name }}
          config: ${{ matrix.config }}

      - if: matrix.project.name == 'UnitTestRunner'
        name: Run UnitTestRunner
        run: ${{ steps.build.outputs.build-dir }}/UnitTestRunner
