name: macOS builds
on: push

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-builds:
    strategy:
      matrix:
        target: [AudioPluginExample,
                 ConsoleAppExample,
                 GuiAppExample]
        config: [Release]
    name: ${{ matrix.target }} (CMake - ${{ matrix.config }})
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build CMake target ${{ matrix.target }}
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ./cmake-build
          configure-options: -G Xcode
          build-type: ${{ matrix.config }}
          target: ${{ matrix.target }}

  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPluginHost},
          {dir: extras, name: Projucer},
          {dir: extras, name: UnitTestRunner},
        ]
        config: [Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: macos-latest
    env:
      PROJECT_PATH: ./${{ matrix.project.dir }}/${{ matrix.project.name }}/Builds/MacOSX
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          xcodebuild -configuration ${{ matrix.config }} \
                     GCC_TREAT_WARNINGS_AS_ERRORS=YES
