on: push

jobs:
  build-projucer-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild -project "./extras/Projucer/Builds/MacOSX/Projucer.xcodeproj" -configuration Release GCC_TREAT_WARNINGS_AS_ERRORS=YES
