on: push

jobs:
  build-xcode-project:
    strategy:
      matrix:
        project: [AudioPerformanceTest, AudioPluginHost, BinaryBuilder, NetworkGraphicsDemo, Projucer, UnitTestRunner]
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild -project ./extras/${{ matrix.project }}/Builds/MacOSX/${{ matrix.project }}.xcodeproj -configuration Release GCC_TREAT_WARNINGS_AS_ERRORS=YES

  build-cmake-projects:
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
        arg: ['-DJUCE_BUILD_EXAMPLES=ON', '-DJUCE_BUILD_EXTRAS=ON']
    runs-on: ${{ matrix.os }}
    steps:
    - if: runner.os == 'Linux'
      run: |
        sudo apt install libasound2-dev libjack-jackd2-dev \
        ladspa-sdk \
        libcurl4-openssl-dev  \
        libfreetype6-dev \
        libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
        libwebkit2gtk-4.0-dev \
        libglu1-mesa-dev mesa-common-dev
    - uses: actions/checkout@v3
    - run: cmake . -B cmake-build ${{ matrix.arg }}
    - run: cmake --build cmake-build
