on: push

jobs:
  build-xcode-project:
    strategy:
      matrix:
        project: [AudioPerformanceTest, AudioPluginHost, BinaryBuilder, NetworkGraphicsDemo, Projucer, UnitTestRunner]
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild -project ./extras/${{ matrix.project }}/Builds/MacOSX/${{ matrix.project }}.xcodeproj -configuration Release GCC_TREAT_WARNINGS_AS_ERRORS=YES
