name: Windows builds
on: push

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-generate:
    name: Generate CMake
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate CMake
        uses: ./.github/actions/generate-cmake
        with:
          generator: Visual Studio 17 2022

  cmake-builds:
    needs: cmake-generate
    strategy:
      matrix:
        target: [AudioPerformanceTest,
                 AudioPluginHost,
                 BinaryBuilder,
                 DemoRunner,
                 NetworkGraphicsDemo,
                 Projucer,
                 UnitTestRunner,
                 AudioPluginExample,
                 ConsoleAppExample,
                 GuiAppExample]
        config: [Debug, Release]
    name: ${{ matrix.target }} (CMake)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build CMake target ${{ matrix.target }}
        uses: ./.github/actions/build-cmake
        with:
          config: ${{ matrix.config }}
          target: ${{ matrix.target }}

  projucer-builds:
    strategy:
      matrix:
        project: [
          {dir: examples, name: DemoRunner},
          {dir: extras, name: AudioPerformanceTest},
          {dir: extras, name: AudioPluginHost},
          {dir: extras, name: BinaryBuilder},
          {dir: extras, name: NetworkGraphicsDemo},
          {dir: extras, name: Projucer},
          {dir: extras, name: UnitTestRunner},
        ]
        config: [Debug, Release]
    name: ${{ matrix.project.name }} (${{ matrix.config }})
    runs-on: windows-latest
    env:
      PROJECT_PATH: ./${{ matrix.project.dir }}/${{ matrix.project.name }}/Builds/VisualStudio2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: msbuild ${{ matrix.project.name }}.sln /t:Build /p:Configuration=${{ matrix.config }} /warnaserror /maxcpucount
