name: Windows builds
on:
  push:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-builds:
    strategy:
      matrix:
        target: [AudioPluginExample,
                 ConsoleAppExample,
                 GuiAppExample,
                 DemoRunner]
        config: [Debug, Release]
    name: ${{ matrix.target }} (CMake - ${{ matrix.config }})
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        shell: cmd
        run: |
          PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin;%PATH%
          cmake . -Bbuild -Werror=dev "-GNinja" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_CXX_FLAGS=-Wno-everything -fuse-ld=lld-link.exe" "-DJUCE_BUILD_EXAMPLES=ON" "-DCMAKE_CXX_CLANG_TIDY=clang-tidy;-checks=modernize-*"
          cmake --build build --parallel 1 --config Debug --target ${{ matrix.target }}
