name: Windows builds
on:
  push:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-builds:
    strategy:
      matrix:
        target: [AudioPluginExample,
                 ConsoleAppExample,
                 GuiAppExample,
                 DemoRunner]
        config: [Debug, Release]
    name: ${{ matrix.target }} (CMake - ${{ matrix.config }})
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build CMake target ${{ matrix.target }}
        uses: ./.github/actions/build-cmake
        with:
          build-dir: ./cmake-build
          generator: Ninja Multi-Config
          config: ${{ matrix.config }}
          target: ${{ matrix.target }}
          configure-args: -DJUCE_BUILD_EXAMPLES=ON -DCMAKE_CXX_CLANG_TIDY=clang-tidy;-checks=modernize-*
